### PR TITLE
create models

### LINKED ISSUE #51: Build Model

### PR DESCRIPTION
**Pull request by xqiu1**
fixes #51

### CODE REVIEW

**Review by 7bw — COMMENTED** [review]
Looks good to me. Maybe add some tests later.

**Comment by xqiu1** [comment]
How to deal with list type?

**Comment by xqiu1** [comment]
I use many-to-many fileld to represent part of lists (if the list is used to store objects), other use text fileld.

**Comment by xqiu1** [comment]
I created a wrong model.py before, the correct one should automatically generated by the command `python manage.py startapp presentation` (I named the app to be presentation)

**Review by 7bw — APPROVED** [review]
Let's go

**Pull request merged**
